let s:wikiurl = "http://wiki.ubuntuusers.de/"

" Open URLs with xdg-open.
function! HandleInyokaURL()
  let a:uri = matchstr(getline("."), '\v%(\[\s*\zs[a-z]*:\/\/[^ >,;]*\ze|\[\s*\zs[^:]*:[^:]{-}:\ze[^[]*\])')
  if a:uri != ""
    " Replace inner wiki links.
    " If set to 1 inner wiki link is not appended at the end but inside the
    " wiki link.
    let a:in = 0
    if ! empty(matchstr(a:uri, '\v^[^:]*:[^:]*:$'))
      let s:uri = substitute(a:uri, "\v\:$", "", "")
      let a:inner = matchstr(a:uri, '\v^[^:]*\ze:')
      let a:part = matchstr(a:uri, '\v^[^:]*:\zs[^:]*\ze:$')
      if a:inner == ""
        let a:uri = s:wikiurl
      elseif a:inner == "apt"
        let a:uri = "apt:"
      elseif a:inner == "archwiki"
        let a:uri = "https://wiki.archlinux.org/index.php/"
      elseif a:inner == "askubuntu"
        let a:uri = "http://askubuntu.com/questions/"
      elseif a:inner == "behind"
        let a:uri = "http://behind.ubuntuusers.de/"
      elseif a:inner == "bug"
        let a:uri = "https://launchpad.net/bugs/"
      elseif a:inner == "calendar"
        let a:uri = "http://ubuntuusers.de/calendar/"
      elseif a:inner == "canonical"
        let a:uri = "http://www.canonical.com/content/"
      elseif a:inner == "canonicalblog"
        let a:uri = "http://blog.canonical.com/"
      elseif a:inner == "category"
        let a:uri = "http://forum.ubuntuusers.de/category/"
      elseif a:inner == "debian"
        let a:uri = "http://wiki.debian.org/"
      elseif a:inner == "debianbug"
        let a:uri = "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug="
      elseif a:inner == "debian_de"
        let a:uri = "http://wiki.debian.org/de/"
      elseif a:inner == "desura"
        let a:uri = "http://www.desura.com/games/"
      elseif a:inner == "dropbox"
        let a:uri = "http://dl.dropbox.com/u/"
      elseif a:inner == "ean"
        let a:uri = "http://www.google.com/search?as_q=ean&safe=off&btnG=Google-Suche#q="
      elseif a:inner == "edubuntu"
        let a:uri = "http://www.edubuntu.org/"
      elseif a:inner == "ext_de"
        let a:uri = "http:"
      elseif a:inner == "ext_en"
        let a:uri = "http://"
      elseif a:inner == "fb"
        let a:uri = "http://www.facebook.com/"
      elseif a:inner == "forum"
        let a:uri = "http://forum.ubuntuusers.de/forum/"
      elseif a:inner == "freecode"
        let a:uri = "http://freecode.com/projects/"
      elseif a:inner == "freshmeat"
        let a:uri = "http://freecode.com/projects/"
      elseif a:inner == "gameolith"
        let a:uri = "http://www.gameolith.eu/game/"
      elseif a:inner == "getdeb"
        let a:uri = "http://www.getdeb.net/software/"
      elseif a:inner == "github"
        let a:uri = "https://github.com/"
      elseif a:inner == "google"
        let a:uri = "http://www.google.de/search?q="
      elseif a:inner == "googlecode"
        let a:uri = "http://code.google.com/p/"
      elseif a:inner == "googlevideo"
        let a:uri = "http://video.google.de/videoplay?docid="
      elseif a:inner == "gplus"
        let a:uri = "https://plus.google.com/"
      elseif a:inner == "holarse"
        let a:uri = "http://www.holarse-linuxgaming.de/wiki/"
      elseif a:inner == "humble"
        let a:uri = "http://www.humblebundle.com/store/product/"
      elseif a:inner == "iawm"
        let a:uri = "http://wayback.archive.org/web/*/http://"
      elseif a:inner == "identica"
        let a:uri = "http://identi.ca/"
      elseif a:inner == "ikhaya"
        let a:uri = "http://ikhaya.ubuntuusers.de/"
      elseif a:inner == "isbn"
        let a:uri = "http://bookzilla.org/shop/action/advancedSearch?action=search&numbers="
      elseif a:inner == "kubuntu"
        let a:uri = "http://www.kubuntu.org/"
      elseif a:inner == "kubuntu-de"
        let a:uri = "http://wiki.kubuntu-de.org/"
      elseif a:inner == "kubuntu_doc"
        let a:uri = "https://wiki.kubuntu.org/"
      elseif a:inner == "lastfm"
        let a:uri = "http://www.lastfm.de/group/"
      elseif a:inner == "launchpad"
        let a:uri = "https://launchpad.net/"
      elseif a:inner == "liflg"
        let a:uri = "http://liflg.org/?catid="
      elseif a:inner == "linuxgaming"
        let a:uri = "http://wiki.linuxgaming.de/index.php/"
      elseif a:inner == "lpcode"
        let a:uri = "https://code.launchpad.net/"
      elseif a:inner == "lpuser"
        let a:uri = "https://launchpad.net/~"
      elseif a:inner == "lubuntu"
        let a:uri = "http://lubuntu.net/"
      elseif a:inner == "man"
        let a:uri = "http://manpages.ubuntu.com/manpages/"
      elseif a:inner == "ml"
        let a:uri = "https://lists.ubuntu.com/archives/"
      elseif a:inner == "moby"
        let a:uri = "http://www.mobygames.com/game/"
      elseif a:inner == "moddb"
        let a:uri = "http://www.moddb.com/"
      elseif a:inner == "mythbuntu"
        let a:uri = "http://www.mythbuntu.org/"
      elseif a:inner == "omgubuntu"
        let a:uri = "http://www.omgubuntu.co.uk/"
      elseif a:inner == "osm"
        let a:uri = "http://wiki.openstreetmap.org/wiki/"
      elseif a:inner == "packages"
        let a:uri = "http://packages.ubuntu.com/search?suite=default&section=all&arch=any&searchon=names&keywords="
      elseif a:inner == "paste"
        let a:uri = "http://paste.ubuntuusers.de/"
      elseif a:inner == "playdeb"
        let a:uri = "http://www.playdeb.net/software/"
      elseif a:inner == "post"
        let a:uri = "http://forum.ubuntuusers.de/post/"
      elseif a:inner == "sourceforge"
        let a:uri = "http://sourceforge.net/projects/"
      elseif a:inner == "sourceforge2"
        let a:in = 1
        let a:uri = 'http://'.a:part.'.sourceforge.net'
      elseif a:inner == "steam"
        let a:in = 1
        let a:uri = 'http://store.steampowered.com/'.a:part.'?l=german'
      elseif a:inner == "tag"
        let a:uri = "http://wiki.ubuntuusers.de/Wiki/Tags?tag="
      elseif a:inner == "ticket"
        let a:uri = "http://trac.inyokaproject.org/ticket/"
      elseif a:inner == "topic"
        let a:uri = "http://forum.ubuntuusers.de/topic/"
      elseif a:inner == "twitter"
        let a:uri = "http://twitter.com/"
      elseif a:inner == "ubuntu"
        let a:uri = "https://wiki.ubuntu.com/"
      elseif a:inner == "ubuntuapps"
        let a:uri = "https://apps.ubuntu.com/cat/applications/"
      elseif a:inner == "uf_forum"
        let a:uri = "http://ubuntuforums.org/forumdisplay.php?f="
      elseif a:inner == "uf_member"
        let a:uri = "http://ubuntuforums.org/member.php?u="
      elseif a:inner == "uf_thread"
        let a:uri = "http://ubuntuforums.org/showthread.php?t="
      elseif a:inner == "ubuntustudio"
        let a:uri = "http://ubuntustudio.org/"
      elseif a:inner == "ubuntu_doc"
        let a:uri = "https://help.ubuntu.com/"
      elseif a:inner == "ubuntu_fr"
        let a:uri = "http://doc.ubuntu-fr.org/"
      elseif a:inner == "ubuntuone"
        let a:uri = "http://ubuntuone.com/"
      elseif a:inner == "vimeo"
        let a:uri = "http://vimeo.com/"
      elseif a:inner == "wikibooks"
        let a:uri = "http://de.wikibooks.org/wiki/"
      elseif a:inner == "wikimedia"
        let a:uri = "http://commons.wikimedia.org/wiki/"
      elseif a:inner == "wikipedia"
        let a:uri = "http://de.wikipedia.org/wiki/"
      elseif a:inner == "wikipedia_en"
        let a:uri = "http://en.wikipedia.org/wiki/"
      elseif a:inner == "xfcedocs"
        let a:uri = "http://docs.xfce.org/"
      elseif a:inner == "xubuntu"
        let a:uri = "http://www.xubuntu.org/"
      elseif a:inner == "youtube"
        let a:uri = "http://www.youtube.com/watch?v="
      endif

      if a:in == 0
        let a:uri = a:uri.a:part
      endif
    endif
    silent exec "!xdg-open '".a:uri."' &" | redraw!
    echo "Open: ".a:uri
  else
    echo "No URI found in line."
  endif
endfunction
map <CR> :call HandleInyokaURL()<CR>
